FROM alpine:3

LABEL author="Taukhid Aji Nurwijayadi"
LABEL company="Belajar Docker" website="https://linktr.ee/taukhidajin"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"